wso2:
  mysql: {enabled: true, host: wso2ei-rdbms-service-mysql, username: wso2carbon, password: wso2carbon,
    driverClass: com.mysql.jdbc.Driver, validationQuery: SELECT 1}
  subscription: {username: '', password: ''}
  deployment:
    wso2ei:
      imageName: wso2ei-integrator
      imageTag: 6.5.0
      replicas: 1
      minReadySeconds: 75
      strategy:
        rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
      livenessProbe: {initialDelaySeconds: 40, periodSeconds: 10}
      readinessProbe: {initialDelaySeconds: 40, periodSeconds: 10}
      resources:
        requests: {memory: 1Gi, cpu: 1000m}
        limits: {memory: 1Gi, cpu: 1000m}
      imagePullPolicy: Always
    wso2eiAnalyticsWorker1:
      imageName: wso2ei-analytics-worker
      imageTag: 6.5.0
      replicas: 1
      minReadySeconds: 30
      strategy:
        rollingUpdate: {maxSurge: 2, maxUnavailable: 0}
      livenessProbe: {initialDelaySeconds: 20, periodSeconds: 10}
      readinessProbe: {initialDelaySeconds: 20, periodSeconds: 10}
      resources:
        requests: {memory: 1Gi, cpu: 1000m}
        limits: {memory: 1Gi, cpu: 1000m}
      imagePullPolicy: Always
    wso2eiAnalyticsWorker2:
      imageName: wso2ei-analytics-worker
      imageTag: 6.5.0
      replicas: 1
      minReadySeconds: 30
      strategy:
        rollingUpdate: {maxSurge: 2, maxUnavailable: 0}
      livenessProbe: {initialDelaySeconds: 20, periodSeconds: 10}
      readinessProbe: {initialDelaySeconds: 20, periodSeconds: 10}
      resources:
        requests: {memory: 1Gi, cpu: 1000m}
        limits: {memory: 1Gi, cpu: 1000m}
      imagePullPolicy: Always
    wso2eiAnalyticsDashbaord:
      imageName: wso2ei-analytics-dashboard
      imageTag: 6.5.0
      replicas: 1
      minReadySeconds: 30
      strategy:
        rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
      livenessProbe: {initialDelaySeconds: 20, periodSeconds: 10}
      readinessProbe: {initialDelaySeconds: 20, periodSeconds: 10}
      resources:
        requests: {memory: 1Gi, cpu: 1000m}
        limits: {memory: 1Gi, cpu: 1000m}
      imagePullPolicy: Always
  centralizedLogging:
    enabled: true
    logstash:
      imageTag: 7.2.0
      elasticsearch: {host: "",
        username: "", password: "", port: ""}
      readinessProbe: {initialDelaySeconds: 90, periodSeconds: 30}
      livenessProbe: {initialDelaySeconds: 90, periodSeconds: 30}
  monitoring:
    enabled: false
    prometheus:
      serviceMonitor:
        labels: {release: monitoring}
      jmxJobName: jmx
kubernetes: {svcaccount: wso2svc-account}
